### PR TITLE
Add metadata and type checks

### PR DESCRIPTION
**Pull request by ximenesuk**
This PR pushes some additional metadata back via the API, this is used for some BGS-only output. I have included this as an additional schema item, `additional_metadata` where all BGS items have keys starting `bgs_`.
```
    "additional_metadata": {
        "bgs_groups": "7 groups identified in file",
        "bgs_proj_rows": "1 data rows in PROJ group",
        "bgs_loca_rows": "1 data rows in LOCA group"
    }
```
In this work the metadata comprises the full text needed as that means it can be handled easily by `Jinja2` with just minor changes, to produce the text output required:
```
7 groups identified in file
1 data rows in PROJ group
1 data rows in LOCA group
```
which provides the same summary as the original data validator.

It might be possible to have multiple templates that could do this in a more generalisable way?

The fixtures have been modified to pass the tests but this output isn't specifically tested for.

This PR is based off of #47

### CODE REVIEW

**Comment by volcan01010** [comment]
I have updated this branch so that it:

+ Includes more information in the `additional_metadata` including group and project names
+ Added a check for coordinates with incorrect type settings
+ Added an option, set via environment variable, to change the `root_path` where the API is served

This solves the top 3 priority items in #30.

Over to you to merge, @ximenesuk.

**Comment by volcan01010** [comment]
Incidentally, I first tried to solve the column type check using pure Pandas functions but in the end I scrapped it and rewrote it as a simple loop.  It's hard to predict when Pandas is the best way to go.

**Comment by ximenesuk** [comment]
I just found this bug testing this PR. The file `Mount Severn- Environment Agency.ags` throws an exception when checking BGS rules with JSON output. Text output is fine.
```
...
  File "./app/routes.py", line 123, in validate
    response = prepare_validation_response(request, data)
  File "./app/routes.py", line 171, in prepare_validation_response
    return ValidationResponse(**response_data, media_type="application/json")
  File "/home/colin/.virtualenvs/ags/lib/python3.8/site-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
data -> 0 -> errors
  Unknown rule: 'Non-numeric coordinate types' (type=assertion_error)
data -> 0
  value could not be parsed to a boolean (type=type_error.bool)
```

It's probably a schema issue, a type may need widening.

**Comment by ximenesuk** [comment]
I'm happy with the PR with this final commit added. Can you double check the code changes and merge if happy @volcan01010 ?

**Pull request merged**
